FROM ubuntu:22.04

EXPOSE 5000

WORKDIR /usr/src

COPY example-frontend/ .

RUN apt-get update; apt-get install -y curl; curl -sL https://deb.nodesource.com/setup_16.x | bash -; apt-get install -y nodejs

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install; npm run build; npm install -g serve

CMD ["serve", "-s", "-l", "5000", "build"]