services:

  simplewebservice:
    image: devopsdockeruh/simple-web-service
    build: .
    volumes:
      - ./output/log.txt:/usr/src/app/text.log
    container_name: simpleweb-server
    ports:
      - 8080:8080
    command: server